### ISSUE TITLE
Allow user to determine file name in OSS bucket

### ISSUE THREAD

**Issue by leixiaoyu** [e10101/multer-ali-oss#1]
Names of files uploaded to OSS are encrypted to HEX values. Why not allow user to determine file names via options in constructor? In my use case, I will need to set file name so that I can categorize files in a bucket.

If you don't mind reviewing, I can put up a PR for this. Let me know.

**Comment by e10101** [comment]
Thanks for your feedback. Let me try to add the feature. When I finished, I will let you know.

## 

update: I just added the custom filename setting function, please try the version 0.0.3.
